# Generated by Django 2.0 on 2019-05-20 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190520_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '教程', 'verbose_name_plural': '教程'},
        ),
    ]
