# Generated by Django 2.0 on 2019-05-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_upload_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload_file',
        ),
    ]
