# Generated by Django 2.0 on 2019-05-20 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('public_time', models.TimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('author', models.CharField(blank=True, max_length=10, verbose_name='文章作者')),
            ],
            options={
                'verbose_name': '文章信息',
                'verbose_name_plural': '文章信息',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='文章种类')),
            ],
            options={
                'verbose_name': '文章种类',
                'verbose_name_plural': '文章种类',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Category', verbose_name='文章种类'),
        ),
    ]
